# output dir will be created by hydra
data_dir: /beegfs/desy/user/ewencedr/data/
output_dir: /beegfs/desy/user/ewencedr/pc-jedi/logs/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/