# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

datamodule:
  _target_: src.datamodules.flow_gen.FlowGeneratedData
  flow_path: /home/ewencedr/deep-learning/data/conditioning.h5
  ctxt_vars:
    - pt
    - mass
    # - num_particles
    # - type
  data_conf:
    jet_type:
      - t
    num_particles: null
    one_hot: False
  batch_size: 1024

sampler_steps:
  # - 200
  # - 200
  # - 50
  - 10

sampler_name:
  - em
  #- euler
  #- ddim
  #- rk
  #- midpoint

load: last

project_name: epic_debug
network_name: 2023-07-18_18-10-03-392032
